version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile-API
    ports:
      - "3000:8080"
    restart: always
    container_name: api
  database:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=BodyPerformance
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    container_name: database
  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@dal.ca"
      PGADMIN_DEFAULT_PASSWORD: "password"
    container_name: pgadmin
    ports:
      - "16547:80"
    depends_on: 
      - database
